const data = {
  products: [
    {
      id: '1',
      name: 'Hatchback ',
      Period:'Monthly',
      price: 1299,
      Services:"Services Provided",
      s1:"10 Days Cleaning",
      s2:"Foam Washes",
      s3:"Deep Cleaning",
      s4:"Nomal Washes",
      image: 'https://www.hdcarwallpapers.com/thumbs/2018/2020_mazda3_hatchback_4k-t2.jpg',
    },
    {
      id: '2',
      Period:'Monthly',
      name: 'Sedan',
      price: 1399,
      Services:"Services Provided",
      s1:"10 Days Cleaning",
      s2:"Foam Washes",
      s3:"Deep Cleaning",
      s4:"Nomal Washes",
      image: 'https://www.hdcarwallpapers.com/thumbs/2018/mercedes_amg_e_53_4matic_2018_4k-t2.jpg',
    },
    {
      id: '3',
      Period:'Monthly',
      name: 'Suv',
      price: 1599,
      Services:"Services Provided",
      s1:"10 Days Cleaning",
      s2:"Foam Washes",
      s3:"Deep Cleaning",
      s4:"Nomal Washes",
      image: 'https://www.ford.com/cmslibs/content/dam/brand_ford/en_us/brand/legacy/nameplate/suvs/21_FRD_EPR_400059_32.jpg/_jcr_content/renditions/cq5dam.web.768.768.jpeg',
    },
    {
      id: '4',
      Period:'Monthly',
      name: 'Mini Suv',
      price:1499,
      Services:"Services Provided",
      s1:"10 Days Cleaning",
      s2:"Foam Washes",
      s3:"Deep Cleaning",
      s4:"Nomal Washes",
      image: 'https://www.topgear.com/sites/default/files/cars-car/image/2017/01/mini_countryman_212_0.jpg',
    },
  ],
};
export default data;
